---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    io.penpot.service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.penpot.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.penpot.network/penpot: "true"
        io.penpot.service: frontend
    spec:
      containers:
        - image: penpotapp/frontend:latest
          name: frontend
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: frontend-env
          volumeMounts:
            - mountPath: /opt/data
              name: data-storage
      restartPolicy: Always
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: local-path-pvc
