---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    io.penpot.service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.penpot.service: redis
  strategy: {}
  template:
    metadata:
      labels:
        io.penpot.network/penpot: "true"
        io.penpot.service: redis
    spec:
      containers:
        - image: redis:7
          name: redis
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
