---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    io.penpot.service: frontend
spec:
  type: LoadBalancer
  selector:
    io.penpot.service: frontend
  ports:
    - name: frontend
      port: 9001
      targetPort: 80
      protocol: TCP
