---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    io.penpot.service: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    io.penpot.service: postgres
