---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    io.penpot.service: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    io.penpot.service: redis
