name: Build

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: npm ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Lint
      run: |
        npm run lint

  status:
    name: Success build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - id: status
        name: Load failure jobs count
        env:
          URL: https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs
          USER: admin:${{ secrets.GITHUB_TOKEN }}
          FILTER: "[.jobs[] | select(.status==\"completed\" and .conclusion==\"failure\") | { status: .conclusion, matrix: .name}] | length"
        run: |
          FAILURE_COUNT=$(curl -X GET -s -u $USER $URL | jq "$FILTER")
          echo "failure_count=$FAILURE_COUNT" >> $GITHUB_OUTPUT
          echo Failure jobs count: $FAILURE_COUNT
      - if: ${{ steps.status.outputs.failure_count > 0 }}
        name: Fail
        run: exit 1

  discord:
    name: Discord notification
    needs: [ status ]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    env:
      DISCORD_USERNAME: github
      DISCORD_ERROR_COLOR: 16726645
      DISCORD_ERROR_AVATAR: https://cdn.jsdelivr.net/gh/tagproject/art/bot/bot-error.png
      DISCORD_EVENT_COLOR: 53759
      DISCORD_EVENT_AVATAR: https://cdn.jsdelivr.net/gh/tagproject/art/bot/bot-event.png
    steps:
    - name: Send error notification after push commit
      if: ${{ contains(needs.*.result, 'failure') && github.event_name == 'push' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        nodetail: true
        username: ${{ env.DISCORD_USERNAME }}
        avatar_url: ${{ env.DISCORD_ERROR_AVATAR }}
        title: 'Build failed :confused:'
        color: ${{ env.DISCORD_ERROR_COLOR }}
        description: |
          **Repository:** `${{ github.repository }}`
          **Branch:** `${{ github.event.ref }}`
          **Author:** [${{ github.event.head_commit.author.username }}](https://github.com/${{ github.event.head_commit.author.username }})
          **Commit:** [${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})
          **Message:**
          `${{ github.event.head_commit.message }}`
    - name: Send error notification for pull_request
      if: ${{ contains(needs.*.result, 'failure') && github.event_name == 'pull_request' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        nodetail: true
        username: ${{ env.DISCORD_USERNAME }}
        avatar_url: ${{ env.DISCORD_ERROR_AVATAR }}
        title: 'Pull request build failed :confused:'
        color: ${{ env.DISCORD_ERROR_COLOR }}
        description: |
          **Repository:** `${{ github.repository }}`
          **Merge:** into `${{ github.event.pull_request.base.ref }}` from `${{ github.event.pull_request.head.ref }}`
          **Title:** ${{ github.event.pull_request.title }} [#${{ github.event.pull_request.number }}](${{github.event.pull_request._links.html.href}})
          **Assignees:** `${{ join(github.event.pull_request.assignees.*.login, ', ') }}`
          **Labels:** `${{ join(github.event.pull_request.labels.*.name, ', ') }}`
    - name: Send success notification for pull_request
      if: ${{ !contains(needs.*.result, 'failure') && github.event_name == 'pull_request' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        nodetail: true
        username: ${{ env.DISCORD_USERNAME }}
        avatar_url: ${{ env.DISCORD_EVENT_AVATAR }}
        title: 'Pull request successfully build :face_with_monocle:'
        color: ${{ env.DISCORD_EVENT_COLOR }}
        description: |
          **Repository:** `${{ github.repository }}`
          **Merge:** into `${{ github.event.pull_request.base.ref }}` from `${{ github.event.pull_request.head.ref }}`
          **Title:** ${{ github.event.pull_request.title }} [#${{ github.event.pull_request.number }}](${{github.event.pull_request._links.html.href}})
          **Assignees:** `${{ join(github.event.pull_request.assignees.*.login, ', ') }}`
          **Labels:** `${{ join(github.event.pull_request.labels.*.name, ', ') }}`
